FROM mellanox/rdma-cni as RDMA-CNI

FROM alpine:3.12

WORKDIR /

LABEL io.k8s.display-name="SR-IOV&&RDMA CNI"

ADD ./bin/sriov /sriov

COPY --from=RDMA-CNI /usr/bin/rdma /

ADD ./k8s-installer/20-tke-sriov-rdma.conflist /

ADD ./k8s-installer/installer.sh /

ENTRYPOINT ["/installer.sh"]
