// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.12.4
// source: nodeservice/node.proto

package nodeservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UnderlayIp string `protobuf:"bytes,1,opt,name=UnderlayIp,proto3" json:"UnderlayIp,omitempty"`
	PodCIDR    string `protobuf:"bytes,2,opt,name=PodCIDR,proto3" json:"PodCIDR,omitempty"`
}

func (x *NodeReq) Reset() {
	*x = NodeReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeservice_node_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeReq) ProtoMessage() {}

func (x *NodeReq) ProtoReflect() protoreflect.Message {
	mi := &file_nodeservice_node_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeReq.ProtoReflect.Descriptor instead.
func (*NodeReq) Descriptor() ([]byte, []int) {
	return file_nodeservice_node_proto_rawDescGZIP(), []int{0}
}

func (x *NodeReq) GetUnderlayIp() string {
	if x != nil {
		return x.UnderlayIp
	}
	return ""
}

func (x *NodeReq) GetPodCIDR() string {
	if x != nil {
		return x.PodCIDR
	}
	return ""
}

type NodeRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    int32  `protobuf:"varint,1,opt,name=Ret,proto3" json:"Ret,omitempty"`
	ErrMsg string `protobuf:"bytes,2,opt,name=ErrMsg,proto3" json:"ErrMsg,omitempty"`
}

func (x *NodeRes) Reset() {
	*x = NodeRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_nodeservice_node_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NodeRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeRes) ProtoMessage() {}

func (x *NodeRes) ProtoReflect() protoreflect.Message {
	mi := &file_nodeservice_node_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeRes.ProtoReflect.Descriptor instead.
func (*NodeRes) Descriptor() ([]byte, []int) {
	return file_nodeservice_node_proto_rawDescGZIP(), []int{1}
}

func (x *NodeRes) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *NodeRes) GetErrMsg() string {
	if x != nil {
		return x.ErrMsg
	}
	return ""
}

var File_nodeservice_node_proto protoreflect.FileDescriptor

var file_nodeservice_node_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x6e, 0x6f,
	0x64, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x07, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x12, 0x1e,
	0x0a, 0x0a, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x6c, 0x61, 0x79, 0x49, 0x70, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x55, 0x6e, 0x64, 0x65, 0x72, 0x6c, 0x61, 0x79, 0x49, 0x70, 0x12, 0x18,
	0x0a, 0x07, 0x50, 0x6f, 0x64, 0x43, 0x49, 0x44, 0x52, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x50, 0x6f, 0x64, 0x43, 0x49, 0x44, 0x52, 0x22, 0x33, 0x0a, 0x07, 0x4e, 0x6f, 0x64, 0x65,
	0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x52, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x52, 0x65, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x45, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x45, 0x72, 0x72, 0x4d, 0x73, 0x67, 0x32, 0xbe, 0x01,
	0x0a, 0x0b, 0x4e, 0x6f, 0x64, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34, 0x0a,
	0x08, 0x49, 0x6e, 0x69, 0x74, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e,
	0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65,
	0x73, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x4e, 0x6f, 0x64, 0x65,
	0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x4e, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x12, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x50,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x4e, 0x6f, 0x64, 0x65, 0x52, 0x65, 0x73, 0x22, 0x00, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x69, 0x6d,
	0x70, 0x43, 0x6f, 0x73, 0x6d, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x57, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_nodeservice_node_proto_rawDescOnce sync.Once
	file_nodeservice_node_proto_rawDescData = file_nodeservice_node_proto_rawDesc
)

func file_nodeservice_node_proto_rawDescGZIP() []byte {
	file_nodeservice_node_proto_rawDescOnce.Do(func() {
		file_nodeservice_node_proto_rawDescData = protoimpl.X.CompressGZIP(file_nodeservice_node_proto_rawDescData)
	})
	return file_nodeservice_node_proto_rawDescData
}

var file_nodeservice_node_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_nodeservice_node_proto_goTypes = []interface{}{
	(*NodeReq)(nil), // 0: NodeProto.NodeReq
	(*NodeRes)(nil), // 1: NodeProto.NodeRes
}
var file_nodeservice_node_proto_depIdxs = []int32{
	0, // 0: NodeProto.NodeService.InitNode:input_type -> NodeProto.NodeReq
	0, // 1: NodeProto.NodeService.AddClusterNode:input_type -> NodeProto.NodeReq
	0, // 2: NodeProto.NodeService.RemoveClusterNode:input_type -> NodeProto.NodeReq
	1, // 3: NodeProto.NodeService.InitNode:output_type -> NodeProto.NodeRes
	1, // 4: NodeProto.NodeService.AddClusterNode:output_type -> NodeProto.NodeRes
	1, // 5: NodeProto.NodeService.RemoveClusterNode:output_type -> NodeProto.NodeRes
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_nodeservice_node_proto_init() }
func file_nodeservice_node_proto_init() {
	if File_nodeservice_node_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_nodeservice_node_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_nodeservice_node_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NodeRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_nodeservice_node_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nodeservice_node_proto_goTypes,
		DependencyIndexes: file_nodeservice_node_proto_depIdxs,
		MessageInfos:      file_nodeservice_node_proto_msgTypes,
	}.Build()
	File_nodeservice_node_proto = out.File
	file_nodeservice_node_proto_rawDesc = nil
	file_nodeservice_node_proto_goTypes = nil
	file_nodeservice_node_proto_depIdxs = nil
}
