// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package nodeservice

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NodeServiceClient is the client API for NodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeServiceClient interface {
	InitNode(ctx context.Context, in *NodeReq, opts ...grpc.CallOption) (*NodeRes, error)
	AddClusterNode(ctx context.Context, in *NodeReq, opts ...grpc.CallOption) (*NodeRes, error)
	RemoveClusterNode(ctx context.Context, in *NodeReq, opts ...grpc.CallOption) (*NodeRes, error)
}

type nodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeServiceClient(cc grpc.ClientConnInterface) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) InitNode(ctx context.Context, in *NodeReq, opts ...grpc.CallOption) (*NodeRes, error) {
	out := new(NodeRes)
	err := c.cc.Invoke(ctx, "/NodeProto.NodeService/InitNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) AddClusterNode(ctx context.Context, in *NodeReq, opts ...grpc.CallOption) (*NodeRes, error) {
	out := new(NodeRes)
	err := c.cc.Invoke(ctx, "/NodeProto.NodeService/AddClusterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nodeServiceClient) RemoveClusterNode(ctx context.Context, in *NodeReq, opts ...grpc.CallOption) (*NodeRes, error) {
	out := new(NodeRes)
	err := c.cc.Invoke(ctx, "/NodeProto.NodeService/RemoveClusterNode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServiceServer is the server API for NodeService service.
// All implementations must embed UnimplementedNodeServiceServer
// for forward compatibility
type NodeServiceServer interface {
	InitNode(context.Context, *NodeReq) (*NodeRes, error)
	AddClusterNode(context.Context, *NodeReq) (*NodeRes, error)
	RemoveClusterNode(context.Context, *NodeReq) (*NodeRes, error)
	mustEmbedUnimplementedNodeServiceServer()
}

// UnimplementedNodeServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNodeServiceServer struct {
}

func (UnimplementedNodeServiceServer) InitNode(context.Context, *NodeReq) (*NodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitNode not implemented")
}
func (UnimplementedNodeServiceServer) AddClusterNode(context.Context, *NodeReq) (*NodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddClusterNode not implemented")
}
func (UnimplementedNodeServiceServer) RemoveClusterNode(context.Context, *NodeReq) (*NodeRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveClusterNode not implemented")
}
func (UnimplementedNodeServiceServer) mustEmbedUnimplementedNodeServiceServer() {}

// UnsafeNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeServiceServer will
// result in compilation errors.
type UnsafeNodeServiceServer interface {
	mustEmbedUnimplementedNodeServiceServer()
}

func RegisterNodeServiceServer(s grpc.ServiceRegistrar, srv NodeServiceServer) {
	s.RegisterService(&NodeService_ServiceDesc, srv)
}

func _NodeService_InitNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).InitNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeProto.NodeService/InitNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).InitNode(ctx, req.(*NodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_AddClusterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).AddClusterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeProto.NodeService/AddClusterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).AddClusterNode(ctx, req.(*NodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _NodeService_RemoveClusterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).RemoveClusterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/NodeProto.NodeService/RemoveClusterNode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).RemoveClusterNode(ctx, req.(*NodeReq))
	}
	return interceptor(ctx, in, info, handler)
}

// NodeService_ServiceDesc is the grpc.ServiceDesc for NodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "NodeProto.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "InitNode",
			Handler:    _NodeService_InitNode_Handler,
		},
		{
			MethodName: "AddClusterNode",
			Handler:    _NodeService_AddClusterNode_Handler,
		},
		{
			MethodName: "RemoveClusterNode",
			Handler:    _NodeService_RemoveClusterNode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nodeservice/node.proto",
}
